version: "3"

services:
  redisapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: vcontu/rclient
    container_name: rclient
    hostname: rclient
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: /config
    volumes:
      - "/host_mnt/c/Users/vcontu/practice/rclient/docker/volume/rclient.properties:/config/rclient.properties"
    restart: on-failure
    networks:
      - redisnet
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
  redis:
    image: "redis:latest"
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - redisnet
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

networks:
  redisnet:
    driver: bridge
